In [173]:
import numpy

In [174]:
vector = [1, 2 , 3] 

In [175]:
print(type(vector))

<class 'list'>


In [176]:
nevector = numpy.array(vector)


In [177]:
nevector.shape

(3,)

In [178]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [179]:
nmatrix = numpy.array(matrix)

In [180]:
narr = numpy.array([1,2,3])
narr

array([1, 2, 3])

In [181]:
numpy.resize(narr,(4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [182]:
narr.resize((3, 3) , refcheck=False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [183]:
o_matrix = numpy.ones((5 , 4))
o_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [184]:
z_matrix = numpy.zeros((4,4))
z_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [185]:
numpy.diag(o_matrix)

array([1., 1., 1., 1.])

In [186]:
o_matrix_int = numpy.ones((4,4) , int)
o_matrix_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [187]:
z_matrix_int = numpy.zeros((4,4))
o_matrix_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [188]:
o_matrix_float = numpy.ones((4,4) , float)
o_matrix_float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [189]:
numpy.vstack([o_matrix,z_matrix])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [190]:
numpy.hstack([o_matrix_int,z_matrix_int])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [191]:
x = numpy.array([1,2,3])
y = numpy.array([4,5,6])

In [192]:
z = x * y
z

array([ 4, 10, 18])

In [193]:
x ** 2

array([1, 4, 9])

In [194]:
x.dot(y)

np.int64(32)

In [195]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [196]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [197]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [198]:
narr.max()

np.int64(3)

In [199]:
narr.min()

np.int64(0)

In [200]:
narr.sum()

np.int64(6)

In [201]:
narr.argmax()

np.int64(2)

In [202]:
narr.mean()

np.float64(0.6666666666666666)

In [203]:
narr.std()

np.float64(1.0540925533894598)

In [204]:
arr_auto = numpy.arange(15)
arr_auto

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [205]:
arr_auto = numpy.arange(15) ** 2
arr_auto

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [206]:
arr_auto[2]

np.int64(4)

In [207]:
arr_auto[1:5]

array([ 1,  4,  9, 16])

In [208]:
arr_auto[:5]

array([ 0,  1,  4,  9, 16])

In [209]:
arr_auto[-2]

np.int64(169)

In [210]:
arr_auto[5:-1:-1]

array([], dtype=int64)

In [211]:
arr_auto[10::-2]

array([100,  64,  36,  16,   4,   0])

In [212]:
arr_auto[5:12:3]

array([ 25,  64, 121])

In [213]:
arr_auto[-6:14:2]

array([ 81, 121, 169])

In [214]:
arr_auto[-10:-2:2]

array([ 25,  49,  81, 121])

In [215]:
mat_arr = numpy.array([[1,+1,-1],
                      [2,+2,-2],
                      [3,+3,-3]])

In [216]:
mat_arr[0:2,1:3]

array([[ 1, -1],
       [ 2, -2]])

In [217]:
mat_arr[::2 , -1]

array([-1, -3])

In [218]:
mat_arr[::2 , -1:]

array([[-1],
       [-3]])

In [219]:
mat_arr[::-1,2:]

array([[-3],
       [-2],
       [-1]])

In [220]:
mat_arr[mat_arr >= 0]

array([1, 1, 2, 2, 3, 3])

In [221]:
mat_arr[ mat_arr <= 0 ] 

array([-1, -2, -3])

In [222]:
mat_arr[ mat_arr >= 1 ]

array([1, 1, 2, 2, 3, 3])

In [223]:
mat_arr >= 0

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

In [224]:
n_mat_arr = mat_arr[-1]
n_mat_arr

array([ 3,  3, -3])

In [225]:
n_mat_arr[:2] = -33
n_mat_arr

array([-33, -33,  -3])

In [226]:
mat_arr

array([[  1,   1,  -1],
       [  2,   2,  -2],
       [-33, -33,  -3]])

In [228]:
n_mat_arr = mat_arr.copy()
n_mat_arr

array([[  1,   1,  -1],
       [  2,   2,  -2],
       [-33, -33,  -3]])

In [230]:
tarr = numpy.random.randint(0,15,(4,3))
tarr

array([[ 2, 13, 12],
       [ 5,  7, 14],
       [ 8,  9, 13],
       [13,  1, 13]], dtype=int32)