In [3]:
import numpy

In [4]:
vector = [1, 2 , 3] 

In [5]:
print(type(vector))

<class 'list'>


In [6]:
nevector = numpy.array(vector)


In [7]:
nevector.shape

(3,)

In [8]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [9]:
nmatrix = numpy.array(matrix)

In [10]:
narr = numpy.array([1,2,3])
narr

array([1, 2, 3])

In [11]:
numpy.resize(narr,(4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [12]:
narr.resize((3, 3) , refcheck=False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
o_matrix = numpy.ones((5 , 4))
o_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
z_matrix = numpy.zeros((4,4))
z_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
numpy.diag(o_matrix)

array([1., 1., 1., 1.])

In [16]:
o_matrix_int = numpy.ones((4,4) , int)
o_matrix_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
z_matrix_int = numpy.zeros((4,4))
o_matrix_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
o_matrix_float = numpy.ones((4,4) , float)
o_matrix_float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
numpy.vstack([o_matrix,z_matrix])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
numpy.hstack([o_matrix_int,z_matrix_int])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [21]:
x = numpy.array([1,2,3])
y = numpy.array([4,5,6])

In [22]:
z = x * y
z

array([ 4, 10, 18])

In [23]:
x ** 2

array([1, 4, 9])

In [24]:
x.dot(y)

np.int64(32)

In [25]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [27]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [28]:
narr.max()

np.int64(3)

In [29]:
narr.min()

np.int64(0)

In [30]:
narr.sum()

np.int64(6)

In [31]:
narr.argmax()

np.int64(2)

In [32]:
narr.mean()

np.float64(0.6666666666666666)

In [33]:
narr.std()

np.float64(1.0540925533894598)

In [34]:
arr_auto = numpy.arange(15)
arr_auto

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arr_auto = numpy.arange(15) ** 2
arr_auto

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [36]:
arr_auto[2]

np.int64(4)

In [37]:
arr_auto[1:5]

array([ 1,  4,  9, 16])

In [38]:
arr_auto[:5]

array([ 0,  1,  4,  9, 16])

In [39]:
arr_auto[-2]

np.int64(169)

In [40]:
arr_auto[5:-1:-1]

array([], dtype=int64)

In [41]:
arr_auto[10::-2]

array([100,  64,  36,  16,   4,   0])

In [42]:
arr_auto[5:12:3]

array([ 25,  64, 121])

In [43]:
arr_auto[-6:14:2]

array([ 81, 121, 169])

In [44]:
arr_auto[-10:-2:2]

array([ 25,  49,  81, 121])

In [45]:
mat_arr = numpy.array([[1,+1,-1],
                      [2,+2,-2],
                      [3,+3,-3]])

In [46]:
mat_arr[0:2,1:3]

array([[ 1, -1],
       [ 2, -2]])

In [47]:
mat_arr[::2 , -1]

array([-1, -3])

In [48]:
mat_arr[::2 , -1:]

array([[-1],
       [-3]])

In [49]:
mat_arr[::-1,2:]

array([[-3],
       [-2],
       [-1]])

In [50]:
mat_arr[mat_arr >= 0]

array([1, 1, 2, 2, 3, 3])

In [51]:
mat_arr[ mat_arr <= 0 ] 

array([-1, -2, -3])

In [52]:
mat_arr[ mat_arr >= 1 ]

array([1, 1, 2, 2, 3, 3])

In [53]:
mat_arr >= 0

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

In [54]:
n_mat_arr = mat_arr[-1]
n_mat_arr

array([ 3,  3, -3])

In [55]:
n_mat_arr[:2] = -33
n_mat_arr

array([-33, -33,  -3])

In [56]:
mat_arr

array([[  1,   1,  -1],
       [  2,   2,  -2],
       [-33, -33,  -3]])

In [57]:
n_mat_arr = mat_arr.copy()
n_mat_arr

array([[  1,   1,  -1],
       [  2,   2,  -2],
       [-33, -33,  -3]])

In [58]:
tarr = numpy.random.randint(0,15,(4,3))
tarr

array([[ 1, 13, 13],
       [13, 13,  7],
       [11,  5, 13],
       [ 7,  4, 13]], dtype=int32)

In [60]:
for t in tarr:
    t = t ** 2
    print(t)

[  1 169 169]
[169 169  49]
[121  25 169]
[ 49  16 169]


In [62]:
list(zip(narr,tarr))

[(array([1, 2, 3]), array([ 1, 13, 13], dtype=int32)),
 (array([0, 0, 0]), array([13, 13,  7], dtype=int32)),
 (array([0, 0, 0]), array([11,  5, 13], dtype=int32))]

In [70]:
n_arr = [1,2,3,5,8,9,4]
n_arr = numpy.array(n_arr)
n_arr

array([1, 2, 3, 5, 8, 9, 4])

In [71]:
len(n_arr) // 2

3

In [73]:
p = n_arr[len(n_arr) // 2]
p

np.int64(5)

In [75]:
l = [x for x in n_arr if x < p]
l

[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [80]:
r = [x for x in n_arr if x > p]
r

[np.int64(8), np.int64(9)]

In [81]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x  < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [86]:
h = [3, 6, 8, 10, 1, 2, 1]
sort = quicksort(h)
print(sort)

[np.int64(1), np.int64(1), np.int64(2), np.int64(3), np.int64(6), np.int64(8), np.int64(10)]


In [87]:
arr = numpy.array([3, 6, 8, 10, 1, 2, 1])
sorted_arr = numpy.sort(arr, kind="quicksort")  
sorted_arr

array([ 1,  1,  2,  3,  6,  8, 10])