In [41]:
import numpy

In [42]:
vector = [1, 2 , 3] 

In [ ]:
print(type(vector))

In [44]:
nevector = numpy.array(vector)


In [ ]:
nevector.shape

In [46]:
matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [47]:
nmatrix = numpy.array(matrix)

In [ ]:
narr = numpy.array([1,2,3])
narr

In [ ]:
numpy.resize(narr,(4, 4))

In [ ]:
narr.resize((3, 3) , refcheck=False)
narr

In [ ]:
o_matrix = numpy.ones((5 , 4))
o_matrix

In [ ]:
z_matrix = numpy.zeros((4,4))
z_matrix

In [ ]:
numpy.diag(o_matrix)

In [ ]:
o_matrix_int = numpy.ones((4,4) , int)
o_matrix_int

In [ ]:
z_matrix_int = numpy.zeros((4,4))
o_matrix_int

In [ ]:
o_matrix_float = numpy.ones((4,4) , float)
o_matrix_float

In [ ]:
numpy.vstack([o_matrix,z_matrix])

In [ ]:
numpy.hstack([o_matrix_int,z_matrix_int])

In [62]:
x = numpy.array([1,2,3])
y = numpy.array([4,5,6])

In [63]:
z = x * y
z

array([ 4, 10, 18])

In [64]:
x ** 2

array([1, 4, 9])

In [65]:
x.dot(y)

np.int64(32)

In [66]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [68]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [69]:
narr.max()

np.int64(3)

In [71]:
narr.min()

np.int64(0)

In [70]:
narr.sum()

np.int64(6)

In [72]:
narr.argmax()

np.int64(2)

In [73]:
narr.mean()

np.float64(0.6666666666666666)

In [74]:
narr.std()

np.float64(1.0540925533894598)

In [75]:
arr_auto = numpy.arange(15)
arr_auto

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
arr_auto = numpy.arange(15) ** 2
arr_auto

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [78]:
arr_auto[2]

np.int64(4)

In [79]:
arr_auto[1:5]

array([ 1,  4,  9, 16])

In [80]:
arr_auto[:5]

array([ 0,  1,  4,  9, 16])

In [81]:
arr_auto[-2]

np.int64(169)

In [84]:
arr_auto[5:-1:-1]

array([], dtype=int64)

In [85]:
arr_auto[10::-2]

array([100,  64,  36,  16,   4,   0])

In [86]:
arr_auto[5:12:3]

array([ 25,  64, 121])

In [87]:
arr_auto[-6:14:2]

array([ 81, 121, 169])

In [88]:
arr_auto[-10:-2:2]

array([ 25,  49,  81, 121])